"""baseline schema — 16 tables + pgvector/pgcrypto + RLS on tenant-owned tables

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-07

Hand-authored (not autogenerated) because Alembic cannot emit extensions or
Row-Level Security. RLS is the non-negotiable isolation layer (constitution
Principle IV) and must be explicit, reviewable, and reversible here.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from keel.infra.orm import TENANT_OWNED_TABLES

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UUID = postgresql.UUID(as_uuid=True)
_JSONB = postgresql.JSONB
_TS = sa.TIMESTAMP(timezone=True)
_NOW = sa.text("now()")
_GEN_UUID = sa.text("gen_random_uuid()")

# Tables in dependency order (parents before children).
_ORDERED_TABLES = (
    "tenants",
    "users",
    "students",
    "courses",
    "prerequisites",
    "corequisites",
    "sections",
    "program_requirements",
    "student_transcript",
    "plans",
    "enrollments",
    "waitlist",
    "request_queue",
    "outbox",
    "audit_log",
    "notifications",
)


def _id_col() -> sa.Column:
    return sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID)


def _tenant_col() -> sa.Column:
    return sa.Column(
        "tenant_id",
        _UUID,
        sa.ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )


def _created_col() -> sa.Column:
    return sa.Column("created_at", _TS, nullable=False, server_default=_NOW)


def upgrade() -> None:
    # --- Extensions (no-op if the DB init already created them) ---
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # 1. tenants (NOT tenant-owned)
    op.create_table(
        "tenants",
        _id_col(),
        sa.Column("slug", sa.String(64), nullable=False, unique=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False, server_default=sa.text("'active'")),
        sa.Column(
            "widget_origin_allowlist",
            _JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        _created_col(),
        sa.CheckConstraint("status IN ('active','suspended','erased')", name="ck_tenants_status"),
    )

    # 2. users
    op.create_table(
        "users",
        _id_col(),
        _tenant_col(),
        sa.Column("email", sa.Text, nullable=False),
        sa.Column("role", sa.Text, nullable=False),
        sa.Column("display_name", sa.Text, nullable=True),
        _created_col(),
        sa.CheckConstraint("role IN ('admin','student')", name="ck_users_role"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )

    # 3. students
    op.create_table(
        "students",
        _id_col(),
        _tenant_col(),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("program_code", sa.Text, nullable=False),
        sa.Column("max_credits_per_term", sa.Integer, nullable=False, server_default=sa.text("18")),
        sa.Column("current_term", sa.Text, nullable=False),
        sa.Column("current_year", sa.Integer, nullable=False),
        _created_col(),
        sa.CheckConstraint("current_term IN ('fall','spring','summer')", name="ck_students_term"),
    )

    # 4. courses
    op.create_table(
        "courses",
        _id_col(),
        _tenant_col(),
        sa.Column("code", sa.Text, nullable=False),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("credits", sa.Integer, nullable=False),
        sa.Column("difficulty", sa.Integer, nullable=False),
        sa.Column("offered_terms", _JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("description", sa.Text, nullable=True),
        _created_col(),
        sa.CheckConstraint("credits > 0", name="ck_courses_credits"),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 5", name="ck_courses_difficulty"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_courses_tenant_code"),
    )

    # 5. prerequisites
    op.create_table(
        "prerequisites",
        _id_col(),
        _tenant_col(),
        sa.Column("course_code", sa.Text, nullable=False),
        sa.Column("requires_code", sa.Text, nullable=False),
        sa.Column("min_grade", sa.Numeric(3, 2), nullable=True),
        sa.UniqueConstraint("tenant_id", "course_code", "requires_code", name="uq_prereq_edge"),
    )

    # 6. corequisites
    op.create_table(
        "corequisites",
        _id_col(),
        _tenant_col(),
        sa.Column("course_code", sa.Text, nullable=False),
        sa.Column("coreq_code", sa.Text, nullable=False),
        sa.UniqueConstraint("tenant_id", "course_code", "coreq_code", name="uq_coreq_edge"),
    )

    # 7. sections
    op.create_table(
        "sections",
        _id_col(),
        _tenant_col(),
        sa.Column("course_code", sa.Text, nullable=False),
        sa.Column("term", sa.Text, nullable=False),
        sa.Column("year", sa.Integer, nullable=False),
        sa.Column("slots", _JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("capacity", sa.Integer, nullable=False),
        sa.Column("enrolled", sa.Integer, nullable=False, server_default=sa.text("0")),
        _created_col(),
        sa.CheckConstraint("capacity >= 0", name="ck_sections_capacity"),
        sa.CheckConstraint("enrolled >= 0 AND enrolled <= capacity", name="ck_sections_enrolled"),
        sa.CheckConstraint("term IN ('fall','spring','summer')", name="ck_sections_term"),
    )

    # 8. program_requirements
    op.create_table(
        "program_requirements",
        _id_col(),
        _tenant_col(),
        sa.Column("program_code", sa.Text, nullable=False),
        sa.Column("group_name", sa.Text, nullable=False),
        sa.Column("required_credits", sa.Integer, nullable=False),
        sa.Column(
            "eligible_course_codes",
            _JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    # 9. student_transcript
    op.create_table(
        "student_transcript",
        _id_col(),
        _tenant_col(),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("course_code", sa.Text, nullable=False),
        sa.Column("term", sa.Text, nullable=False),
        sa.Column("year", sa.Integer, nullable=False),
        sa.Column("grade", sa.Numeric(3, 2), nullable=True),
        sa.Column("passed", sa.Boolean, nullable=False, server_default=sa.text("false")),
    )

    # 10. plans
    op.create_table(
        "plans",
        _id_col(),
        _tenant_col(),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("version", sa.Integer, nullable=False, server_default=sa.text("1")),
        sa.Column("status", sa.Text, nullable=False, server_default=sa.text("'draft'")),
        sa.Column("plan_data", _JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("validated_at", _TS, nullable=True),
        _created_col(),
        sa.CheckConstraint(
            "status IN ('draft','active','archived','stale')", name="ck_plans_status"
        ),
    )
    # At most one ACTIVE plan per (tenant, student).
    op.create_index(
        "uq_plans_one_active",
        "plans",
        ["tenant_id", "student_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )

    # 11. enrollments
    op.create_table(
        "enrollments",
        _id_col(),
        _tenant_col(),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "section_id",
            _UUID,
            sa.ForeignKey("sections.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("status", sa.Text, nullable=False, server_default=sa.text("'enrolled'")),
        sa.Column("idempotency_key", sa.Text, nullable=False),
        _created_col(),
        sa.CheckConstraint("status IN ('enrolled','dropped')", name="ck_enrollments_status"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_enrollments_idempotency"),
    )

    # 12. waitlist
    op.create_table(
        "waitlist",
        _id_col(),
        _tenant_col(),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "section_id",
            _UUID,
            sa.ForeignKey("sections.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer, nullable=False),
        _created_col(),
    )

    # 13. request_queue
    op.create_table(
        "request_queue",
        _id_col(),
        _tenant_col(),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("type", sa.Text, nullable=False),
        sa.Column("payload", _JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", sa.Text, nullable=False, server_default=sa.text("'pending'")),
        _created_col(),
        sa.Column("resolved_at", _TS, nullable=True),
        sa.CheckConstraint(
            "type IN ('petition','major_change','graduation')", name="ck_request_type"
        ),
        sa.CheckConstraint("status IN ('pending','approved','rejected')", name="ck_request_status"),
    )

    # 14. outbox
    op.create_table(
        "outbox",
        _id_col(),
        _tenant_col(),
        sa.Column("kind", sa.Text, nullable=False),
        sa.Column("payload", _JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("published_at", _TS, nullable=True),
        _created_col(),
        sa.CheckConstraint("kind IN ('email','notification')", name="ck_outbox_kind"),
    )

    # 15. audit_log (append-only; bigserial id)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        _tenant_col(),
        sa.Column("actor", sa.Text, nullable=False),
        sa.Column("action", sa.Text, nullable=False),
        sa.Column("before", _JSONB, nullable=True),
        sa.Column("after", _JSONB, nullable=True),
        _created_col(),
    )

    # 16. notifications
    op.create_table(
        "notifications",
        _id_col(),
        _tenant_col(),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text, nullable=False),
        sa.Column("body", sa.Text, nullable=False),
        sa.Column("read_at", _TS, nullable=True),
        _created_col(),
    )

    # Helpful index for tenant-scoped scans on the busiest child tables.
    for table in TENANT_OWNED_TABLES:
        op.create_index(f"ix_{table}_tenant_id", table, ["tenant_id"])

    # --- Row-Level Security on every tenant-owned table ---
    for table in TENANT_OWNED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
              WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )


def downgrade() -> None:
    # Policies and indexes drop with their tables; drop children before parents.
    for table in reversed(_ORDERED_TABLES):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    # Extensions are left in place (harmless, may be shared); schema is now empty.
