"""Phase 2 — programs, student holds, student_preferences, rag_chunks

Revision ID: 0002_phase2
Revises: 0001_baseline
Create Date: 2026-06-15

Hand-authored (not autogenerated). Additive — existing tables unchanged.
New tables: programs, student_preferences, rag_chunks.
New columns: students.program_id, students.has_hold, students.hold_reason,
             program_requirements.program_id.
RLS added for all new tenant-owned tables.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_phase2"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UUID = postgresql.UUID(as_uuid=True)
_TS = sa.TIMESTAMP(timezone=True)
_NOW = sa.text("now()")
_GEN_UUID = sa.text("gen_random_uuid()")

_NEW_TENANT_OWNED: tuple[str, ...] = ("programs", "student_preferences", "rag_chunks")


def upgrade() -> None:
    # 1. programs — must come before students/program_requirements FKs
    op.create_table(
        "programs",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column(
            "tenant_id",
            _UUID,
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("code", sa.Text, nullable=False),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("degree_type", sa.Text, nullable=False, server_default=sa.text("'BS'")),
        sa.Column(
            "total_credits_required",
            sa.Integer,
            nullable=False,
            server_default=sa.text("120"),
        ),
        sa.Column("description", sa.Text, nullable=True),
        sa.UniqueConstraint("tenant_id", "code", name="uq_programs_tenant_code"),
    )
    op.create_index("ix_programs_tenant_id", "programs", ["tenant_id"])

    # 2. students — additive columns
    op.add_column(
        "students",
        sa.Column(
            "program_id",
            _UUID,
            sa.ForeignKey("programs.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.add_column(
        "students",
        sa.Column(
            "has_hold", sa.Boolean, nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column("students", sa.Column("hold_reason", sa.Text, nullable=True))

    # 3. program_requirements — additive program_id FK
    op.add_column(
        "program_requirements",
        sa.Column(
            "program_id",
            _UUID,
            sa.ForeignKey("programs.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )

    # 4. student_preferences
    op.create_table(
        "student_preferences",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column(
            "tenant_id",
            _UUID,
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "student_id",
            _UUID,
            sa.ForeignKey("students.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "response_style",
            sa.Text,
            nullable=False,
            server_default=sa.text("'detailed'"),
        ),
        sa.Column(
            "language", sa.Text, nullable=False, server_default=sa.text("'en'")
        ),
        sa.Column(
            "difficulty_preference",
            sa.Text,
            nullable=False,
            server_default=sa.text("'any'"),
        ),
        sa.Column("career_interest", sa.Text, nullable=True),
        sa.Column("created_at", _TS, nullable=False, server_default=_NOW),
        sa.Column("updated_at", _TS, nullable=False, server_default=_NOW),
        sa.UniqueConstraint(
            "tenant_id", "student_id", name="uq_student_preferences_tenant_student"
        ),
        sa.CheckConstraint(
            "response_style IN ('brief','detailed')",
            name="ck_sprefs_response_style",
        ),
        sa.CheckConstraint(
            "difficulty_preference IN ('light','medium','heavy','any')",
            name="ck_sprefs_difficulty",
        ),
    )
    op.create_index("ix_student_preferences_tenant_id", "student_preferences", ["tenant_id"])

    # 5. rag_chunks — vector(1024) requires raw DDL for the column type
    op.execute("""
        CREATE TABLE rag_chunks (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
            chunk_id    TEXT NOT NULL,
            source      TEXT NOT NULL,
            type        TEXT NOT NULL,
            code        TEXT,
            doc         TEXT,
            section     TEXT,
            content     TEXT NOT NULL,
            embedding   vector(1024),
            lang        TEXT NOT NULL DEFAULT 'en',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_rag_chunks_tenant_chunk UNIQUE (tenant_id, chunk_id),
            CONSTRAINT ck_rag_chunks_type CHECK (type IN ('course', 'policy'))
        )
    """)
    op.create_index("ix_rag_chunks_tenant_id", "rag_chunks", ["tenant_id"])
    # HNSW index for dense cosine retrieval (pgvector must be loaded).
    op.execute(
        "CREATE INDEX ix_rag_chunks_embedding ON rag_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # GIN expression index for full-text retrieval (no stored tsvector column).
    op.execute(
        "CREATE INDEX ix_rag_chunks_fts ON rag_chunks "
        "USING gin(to_tsvector('english', content))"
    )

    # 6. RLS on every new tenant-owned table (same policy as baseline).
    for table in _NEW_TENANT_OWNED:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
              WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)
            """
        )


def downgrade() -> None:
    for table in reversed(_NEW_TENANT_OWNED):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")

    op.drop_column("program_requirements", "program_id")
    op.drop_column("students", "hold_reason")
    op.drop_column("students", "has_hold")
    op.drop_column("students", "program_id")
